name: scan_zeit
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # firebase
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0

  # state management
  flutter_bloc: ^7.0.0

  # ui
  rflutter_alert: ^2.0.2
  flutter_neumorphic: ^3.0.3
  flutter_spinkit: "^4.1.2"
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  auto_size_text: ^2.1.0

  # QR
  pretty_qr_code: ^2.0.1
  qr_code_scanner: ^0.4.0

  # misc
  url_launcher: ^6.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/cart.svg
    - assets/svg/sign_in.svg
    - assets/svg/slide_1.svg
    - assets/svg/slide_2.svg
    - assets/svg/slide_3.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

